
# IF none don't use
# default days : 1day
DATABASE_UPDATE_DURATION_DAYS = None
DATABASE_UPDATE_DURATION_HOURS = None
DATABASE_UPDATE_DURATION_MINUTES = None
DATABASE_UPDATE_DURATION_SECONDS = 5
MAX_ORDER_LIMIT = 15