# Generated by Django 4.0.2 on 2022-05-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=None, max_length=20)),
                ('product_id', models.SmallIntegerField(default=None)),
                ('product_name', models.CharField(default=None, max_length=25)),
                ('watt', models.FloatField(default=None)),
                ('company', models.CharField(default=None, max_length=15)),
                ('amount', models.FloatField(default=None)),
                ('quantity', models.SmallIntegerField(default=None)),
                ('wireLength', models.FloatField(default=None)),
                ('wireColor', models.CharField(default=None, max_length=10)),
                ('customerName', models.CharField(default=None, max_length=15)),
                ('customerPhNumber', models.CharField(default=None, max_length=15)),
                ('customerAddress', models.CharField(default=None, max_length=25)),
                ('customerPinCode', models.CharField(default=None, max_length=7)),
                ('customerLandMark', models.CharField(default=None, max_length=25)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Delivered',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=None, max_length=20)),
                ('product_id', models.SmallIntegerField(default=None)),
                ('product_name', models.CharField(default=None, max_length=25)),
                ('watt', models.FloatField(default=None)),
                ('company', models.CharField(default=None, max_length=15)),
                ('amount', models.FloatField(default=None)),
                ('quantity', models.SmallIntegerField(default=None)),
                ('wireLength', models.FloatField(default=None)),
                ('wireColor', models.CharField(default=None, max_length=10)),
                ('customerName', models.CharField(default=None, max_length=15)),
                ('customerPhNumber', models.CharField(default=None, max_length=15)),
                ('customerAddress', models.CharField(default=None, max_length=25)),
                ('customerPinCode', models.CharField(default=None, max_length=7)),
                ('customerLandMark', models.CharField(default=None, max_length=25)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
